name: Gemini AI Code Reviewer

on:
  pull_request:
    types: [review_requested, assigned]

jobs:
  review-code:
    if: >
      github.actor.login == github.repository_owner && (
      github.event.requested_reviewer.login == 'ai-agent-net' || 
      github.event.assignee.login == 'ai-agent-net')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Test Gemini Review
        uses: Val-d-emar/gemini-review@main
        with:
          gemini_api_key: ${{ secrets.GEMINI_KEY }}
          github_token: ${{ secrets.AI_AGENT_PAT }}
          review_language: "Russian"
          approval_required: false
          comment_title: "# 🤖 Gemini AI Code Review"
          agent_model: "gemini-2.5-flash"
